version: "3.8"

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_DB: apartment_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nishant2308
    ports:
      - "5432:5432"   # Container port 5432 exposed to VM (guest) port 5432
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apartment-backend
    ports:
      - "5000:4545"  # Access backend via http://localhost:5000
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: apartment_management
      DATABASE_USER: postgres
      DATABASE_PASSWORD: nishant2308
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: apartment-frontend:latest
    container_name: apartment-frontend
    ports:
      - "3000:80"   # Access frontend via http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
